### ISSUE TITLE
[FEAT] 유저, 회사, 카페 도메인 초기 설정

### ISSUE THREAD

**Issue by OJOJIN** [Kusitms-28th-Kukathon-F/Backend#2]
**Feature Request**
기능 설명 : 유저, 회사, 카페 도메인 만듭니다

**Branch Name**
생성 브랜치 이름 : feat/2-domains

**To-Do List**
- [x] 유저 엔티티, 레포 생성
- [x] 회사 엔티티, 레포 생성
- [x] 카페 엔티티, 레포 생성
