### ISSUE TITLE
[FEAT] 부서, 텀블러 도메인 초기 설정

### ISSUE THREAD

**Issue by hojeong2747** [Kusitms-28th-Kukathon-F/Backend#3]
**Feature Request**
기능 설명 : 부서, 텀블러 도메인 만듭니다

**Branch Name**
생성 브랜치 이름 : feat/3-domains

**To-Do List**
- [x] 부서 엔티티, 레포 설정
- [x] 텀블러-현재 엔티티, 레포 설정
- [x] 텀블러-내역 엔티티, 레포 설정
